### ISSUE TITLE
Consider submitting this as a GOV.UK community tool

### ISSUE THREAD

**Issue by querkmachine** [chrisadesign/GOV.UK-Design-System-Nova-snippets#1]
Hi Chris!

My name is Kim. I work on the GOV.UK Design System team—I'm also a Nova user and casual extension developer—so naturally I was intrigued to see this pop up in the extension library (if just that I've been very, very slowly building the same thing 😅).

I'm not sure if you're aware, but we list extensions like this on the [resources and tools](https://design-system.service.gov.uk/community/resources-and-tools/#write-code) page of our website so that the community can find them easier.

We would require some changes (mostly around documentation) so that your extension is compliant with [our contribution criteria](https://design-system.service.gov.uk/community/contribution-criteria/#developing-a-community-resource-or-tool), but if you're willing and wish to do so, it'd be great to see it listed with the others! Just [open an issue](https://github.com/alphagov/govuk-design-system/issues/new) with us when you're ready.

Thanks!
~ Kim

**Comment by chrisadesign** [comment]
Thanks @querkmachine – I'll take a look at the guide and see what I have to do!
